name: "Tag & Deploy Action"

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Read Version
      uses: nyaayaya/package-version@v1
      id: node-version
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ env.PACKAGE_VERSION }}"
        release_name: "v${{ env.PACKAGE_VERSION }}"
